version: '{build}'
image: Visual Studio 2019
build_script:
- ps: msbuild -noLogo -verbosity:minimal -restore -p:Configuration=Release
test_script:
- ps: dotnet test -c Release --no-build --verbosity=normal
artifacts:
- path: '**\Release\*.nupkg'
  name: NuGet
